# yamllint disable-file
# This file is not valid YAML because it is a Go template
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-netbox-proxy.serviceAccountName" . }}
  labels:
    {{- include "go-netbox-proxy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
