name: Build and Push Container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_BASENAME: 'riege/go-netbox-proxy'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3


      # Required for docker/build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GHCR_LOGIN_SERVER }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Determine Image Tags
        id: tags
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.GHCR_LOGIN_SERVER }}/${{ env.IMAGE_BASENAME }}
          sep-tags: ','
          flavor: |
            latest=false
          tags: |
            type=ref,event=pr
            type=sha,enable=${{ github.event_name == 'push' }},prefix=${{ github.event.repository.default_branch }}-${{ github.run_number }}-

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
